In [1]:
import pandas as pd
df = pd.read_excel('all_students.xlsx')
df

       姓名  國文  英文   數學  社會   自然
0    stu1  54  95   50  67   58
1    stu2  59  80   54  75   97
2    stu3  98  69   75  84   75
3    stu4  82  75   76  96   56
4    stu5  86  88   68  90   64
5    stu6  59  57   96  80   93
6    stu7  88  87   86  99   58
7    stu8  83  88   84  93   86
8    stu9  63  81   95  63   56
9   stu10  63  96   99  52   92
10  stu11  97  82   99  84   52
11  stu12  81  97   61  68   82
12  stu13  87  84   87  52   77
13  stu14  59  76   85  74   75
14  stu15  89  91   77  55   83
15  stu16  89  90   53  63   86
16  stu17  62  74   88  56   85
17  stu18  80  85   53  67   62
18  stu19  60  93   82  86   96
19  stu20  96  61   89  69  100
20  stu21  55  72  100  60   94
21  stu22  57  97   61  68   95
22  stu23  80  56   54  79   83
23  stu24  65  62   59  92   94
24  stu25  81  55   88  84   92
25  stu26  71  79   58  83   94
26  stu27  64  79   91  74   82
27  stu28  81  74   66  89   90
28  stu29  57  88   96  69   60
29  stu30  93  88   72  91   58
30  stu31  84  69   72  87   64
31  stu32  89  60   86  87   82
32  stu33  90  89   86  97   79
33  stu34  67  67   91  71   87
34  stu35  56  76   86  89   81
35  stu36  90  51   86  97   54
36  stu37  80  55   98  77   95
37  stu38  99  95   58  94   84
38  stu39  95  78   70  63   96
39  stu40  62  93   83  98   99
40  stu41  72  77   53  97   53
41  stu42  72  98   81  93   69
42  stu43  98  94   65  81   55
43  stu44  66  68   63  95   96
44  stu45  56  68   98  82   90
45  stu46  66  61   77  51   86
46  stu47  98  91   61  55   90
47  stu48  54  54   51  98   75
48  stu49  89  76   75  90   85
49  stu50  74  61   65  81  100