In [3]:
import numpy as np
import pandas as pd
result=pd.read_csv('ex6.csv')
result.index.name = "編號"
result

           one       two     three      four key
編號
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

In [6]:
newResult = result.reset_index().set_index(['key','編號'])
newResult

               one       two     three      four
key 編號
L   0     0.467976 -0.038649 -0.295344 -1.824726
B   1    -0.358893  1.404453  0.704965 -0.200638
G   2    -0.501840  0.659254 -0.421691 -0.057688
R   3     0.204886  1.074134  1.388361 -0.982404
Q   4     0.354628 -0.133116  0.283763 -0.837063
...            ...       ...       ...       ...
L   9995  2.311896 -0.417070 -1.409599 -0.515821
E   9996 -0.479893 -0.650419  0.745152 -0.646038
K   9997  0.523331  0.787112  0.486066  1.093156
G   9998 -0.362559  0.598894 -1.843201  0.887292
0   9999 -0.096376 -1.012999 -0.657431 -0.573315

[10000 rows x 4 columns]

In [12]:
newResult=newResult.sort_index(level='key')
newResult

               one       two     three      four
key 編號
0   101  -0.039105 -0.069510 -1.358052 -0.292859
    142   0.210544 -0.909438  0.903900  0.471579
    168   0.947171  0.328539  0.194055 -0.530855
    197  -0.158497  1.349013 -0.475158 -1.033059
    429  -0.203604 -0.371016 -0.120285 -1.316813
...            ...       ...       ...       ...
Z   9774 -1.649719 -0.588896 -0.542998 -1.429529
    9878 -1.023229 -1.664268  1.294334  0.333396
    9901 -0.759939  0.105655  0.051760  1.124987
    9942 -0.030498 -0.380566  0.482507  0.004529
    9972 -1.627051 -0.978151  0.154745 -1.229037

[10000 rows x 4 columns]

In [14]:
newResult['one']

key  編號
0    101    -0.039105
     142     0.210544
     168     0.947171
     197    -0.158497
     429    -0.203604
               ...
Z    9774   -1.649719
     9878   -1.023229
     9901   -0.759939
     9942   -0.030498
     9972   -1.627051
Name: one, Length: 10000, dtype: float64

In [15]:
newResult.loc['0']

           one       two     three      four
編號
101  -0.039105 -0.069510 -1.358052 -0.292859
142   0.210544 -0.909438  0.903900  0.471579
168   0.947171  0.328539  0.194055 -0.530855
197  -0.158497  1.349013 -0.475158 -1.033059
429  -0.203604 -0.371016 -0.120285 -1.316813
...        ...       ...       ...       ...
9811 -0.197311  1.499384 -0.450783 -0.543044
9866 -0.751565  1.868232  0.088694  0.470143
9948 -0.891974  0.507888 -0.220683  0.062233
9963 -0.830696  2.152076  1.159642  1.237279
9999 -0.096376 -1.012999 -0.657431 -0.573315

[151 rows x 4 columns]

In [18]:
newSerial = newResult['one']
newSerial

key  編號
0    101    -0.039105
     142     0.210544
     168     0.947171
     197    -0.158497
     429    -0.203604
               ...
Z    9774   -1.649719
     9878   -1.023229
     9901   -0.759939
     9942   -0.030498
     9972   -1.627051
Name: one, Length: 10000, dtype: float64

In [19]:
newSerial.unstack()

編號,0,1,2,3,4,5,6,7,8,9,...,9990,9991,9992,9993,9994,9995,9996,9997,9998,9999
key,,,,,,,,,,,,,,,,,,,,,
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.096376
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.370769,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.301214,NaN,NaN,NaN,NaN,NaN,NaN,NaN
B,NaN,-0.358893,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
D,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,-0.479893,NaN,NaN,NaN
F,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
G,NaN,NaN,-0.50184,NaN,NaN,NaN,NaN,NaN,NaN,-1.740877,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.362559,NaN
H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.068804,NaN,NaN,NaN,NaN,NaN
I,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
J,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
K,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.913135,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.523331,NaN,NaN
L,0.467976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2.311896,NaN,NaN,NaN,NaN
M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
N,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
O,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Q,NaN,NaN,NaN,NaN,0.354628,1.81748,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
R,NaN,NaN,NaN,0.204886,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
S,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.35848,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
U,NaN,NaN,NaN,NaN,NaN,NaN,-0.776764,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
V,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
W,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,-0.40998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.821117,NaN,NaN,NaN,NaN,NaN,NaN
Y,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
newSerial.groupby(level='key').sum()

key
0     1.665408
1    11.425734
2   -12.027358
3    42.100302
4     3.369031
5   -21.339628
6    23.546088
7    13.590415
8    -0.013861
9     9.765136
A    38.897269
B    15.440654
C     7.088463
D     2.301488
E     7.847879
F    26.900181
G   -17.480410
H    -7.082552
I     8.148561
J    16.241878
K    51.695215
L    17.545360
M     1.186659
N    14.999531
O   -10.002795
P     9.425316
Q   -13.331859
R    38.933116
S    23.171948
T    48.116511
U    16.968534
V    -3.523774
W    49.312915
X    27.783672
Y    16.990201
Z    -2.153618
Name: one, dtype: float64

In [21]:
newSerial.groupby(level='key').describe()

,count,mean,std,min,25%,50%,75%,max
key,,,,,,,,
0,151.0,0.011029,0.959541,-2.825997,-0.580527,0.005817,0.629865,2.455329
1,146.0,0.078258,0.959080,-2.576925,-0.414999,0.166625,0.676484,2.455329
2,152.0,-0.079127,0.954594,-2.825997,-0.772981,-0.093693,0.527847,1.915538
3,162.0,0.259878,0.995871,-2.825997,-0.356773,0.283128,0.999538,2.487347
4,171.0,0.019702,0.943016,-1.946231,-0.647876,-0.003943,0.692476,2.487347
5,157.0,-0.135921,0.948006,-2.405019,-0.838191,-0.109962,0.554389,2.317658
6,166.0,0.141844,0.960701,-2.825997,-0.521073,0.173946,0.871169,2.403216
7,164.0,0.082868,1.020554,-2.548389,-0.678063,0.086778,0.770236,2.833891
8,162.0,-0.000086,0.902729,-2.576925,-0.665566,-0.020713,0.569025,2.130822
9,150.0,0.065101,0.896976,-2.286471,-0.544930,0.062795,0.610179,2.455329
A,320.0,0.121554,0.896847,-2.687335,-0.411176,0.120263,0.746474,2.487654
B,302.0,0.051128,0.946063,-2.576925,-0.650798,0.109848,0.759167,2.412396
C,286.0,0.024785,0.996719,-2.329398,-0.674944,-0.044935,0.703701,2.833891
D,320.0,0.007192,0.975519,-3.726864,-0.677415,0.050266,0.656251,2.343104
E,368.0,0.021326,0.970214,-3.726864,-0.638959,-0.002634,0.656846,2.487654
F,335.0,0.080299,0.936355,-2.548389,-0.524299,0.031621,0.673501,2.403216
G,308.0,-0.056755,0.936773,-2.286471,-0.700917,-0.092465,0.642133,2.833891
H,330.0,-0.021462,0.913329,-2.687335,-0.629130,-0.038145,0.647354,2.487347
I,327.0,0.024919,0.889084,-2.576925,-0.613167,0.082738,0.613665,2.412396
J,337.0,0.048195,0.980313,-3.726864,-0.634580,0.042611,0.767857,2.833891
K,334.0,0.154776,0.980974,-2.825997,-0.556287,0.170434,0.864744,2.412396
L,346.0,0.050709,0.936662,-2.825997,-0.617155,0.029555,0.681426,2.403216
M,338.0,0.003511,1.003811,-3.726864,-0.725957,-0.046704,0.682939,2.487654
N,306.0,0.049018,0.974226,-3.726864,-0.673222,-0.005671,0.768561,2.833891
O,343.0,-0.029163,0.958823,-2.548389,-0.697644,0.000147,0.609210,2.487654
P,324.0,0.029090,0.929637,-2.338187,-0.546410,0.038958,0.681823,2.412396
Q,340.0,-0.039211,0.953211,-2.825997,-0.688186,-0.005909,0.574804,2.130822
R,318.0,0.122431,0.988772,-3.726864,-0.504874,0.112141,0.763877,2.487347
S,308.0,0.075234,0.948868,-2.825997,-0.560466,0.084080,0.741008,2.487654
T,304.0,0.158278,0.965638,-2.687335,-0.562367,0.187761,0.865151,2.455329
U,326.0,0.052051,0.892629,-2.405019,-0.518820,0.066896,0.698213,2.833891
V,328.0,-0.010743,0.895939,-2.405019,-0.670342,-0.000590,0.532324,2.833891
W,305.0,0.161682,0.930805,-2.329398,-0.481685,0.100228,0.826460,2.833891
X,364.0,0.076329,0.908127,-2.825997,-0.568435,0.085011,0.703516,2.455329
Y,314.0,0.054109,0.898226,-2.548389,-0.632135,0.085565,0.639427,2.343104
Z,288.0,-0.007478,0.999686,-3.726864,-0.562015,0.018572,0.655023,2.412396