In [3]:
import numpy as np
import pandas as pd

scores = np.random.randint(50,101,size=(50,5))
scores

array([[ 91,  53,  68,  72,  65],
       [ 84,  88,  88,  88,  53],
       [ 70,  79,  86,  83,  57],
       [ 74,  59,  50,  73,  90],
       [ 62,  79,  75,  89,  81],
       [ 84,  91,  90,  68, 100],
       [ 65,  50, 100,  74,  89],
       [ 66,  95,  66,  92,  79],
       [ 90,  50,  83,  75,  94],
       [ 66,  99,  58,  94,  60],
       [ 73,  59,  51,  58,  85],
       [ 66,  73,  82,  52,  56],
       [ 53,  54,  99,  92,  84],
       [ 67,  75,  53,  70,  65],
       [ 65,  68,  58,  89,  65],
       [ 59,  57,  71,  70,  60],
       [ 95,  90,  99,  96,  76],
       [ 74,  54,  57,  83,  73],
       [ 63,  89,  95,  89,  56],
       [ 62,  60,  92,  70,  61],
       [ 81,  79,  63,  56,  68],
       [ 64,  80,  87, 100,  52],
       [ 63,  58, 100,  72,  74],
       [ 62,  71,  54,  50,  96],
       [ 85,  78,  84,  94,  54],
       [ 75,  68,  82,  55,  76],
       [ 91,  76,  82,  93,  88],
       [ 59,  58,  62,  76,  99],
       [ 78,  80,  60,  78,  61],
       [ 52,  62,  89,  53,  65],
       [ 88,  77,  85,  89,  95],
       [ 55,  82,  78,  60,  55],
       [ 57,  96,  62,  56,  62],
       [ 61,  62,  65,  99,  70],
       [ 57,  60,  93,  84,  64],
       [ 55,  64,  62,  81,  64],
       [ 98,  52,  81,  81,  85],
       [ 87,  71,  82,  84,  92],
       [ 68,  99,  62,  64,  61],
       [ 69,  68,  61,  80,  62],
       [ 61,  65,  85,  97,  73],
       [ 64, 100,  98,  53,  57],
       [ 88,  64,  94,  57,  83],
       [ 60,  71,  55,  82,  95],
       [ 82,  62,  58,  92,  65],
       [100,  89,  92,  83,  95],
       [ 73,  79,  54,  98,  70],
       [ 87,  67,  83,  67,  96],
       [ 77,  77,  53,  97,  89],
       [ 94,  50,  84,  91,  80]])

In [4]:
class1 = pd.DataFrame(scores,
             index=[f'學生{v}' for v in range(1,51)],
             columns=['國文','英文','數學','自然','地理'])
class1

       國文   英文   數學   自然   地理
學生1    91   53   68   72   65
學生2    84   88   88   88   53
學生3    70   79   86   83   57
學生4    74   59   50   73   90
學生5    62   79   75   89   81
學生6    84   91   90   68  100
學生7    65   50  100   74   89
學生8    66   95   66   92   79
學生9    90   50   83   75   94
學生10   66   99   58   94   60
學生11   73   59   51   58   85
學生12   66   73   82   52   56
學生13   53   54   99   92   84
學生14   67   75   53   70   65
學生15   65   68   58   89   65
學生16   59   57   71   70   60
學生17   95   90   99   96   76
學生18   74   54   57   83   73
學生19   63   89   95   89   56
學生20   62   60   92   70   61
學生21   81   79   63   56   68
學生22   64   80   87  100   52
學生23   63   58  100   72   74
學生24   62   71   54   50   96
學生25   85   78   84   94   54
學生26   75   68   82   55   76
學生27   91   76   82   93   88
學生28   59   58   62   76   99
學生29   78   80   60   78   61
學生30   52   62   89   53   65
學生31   88   77   85   89   95
學生32   55   82   78   60   55
學生33   57   96   62   56   62
學生34   61   62   65   99   70
學生35   57   60   93   84   64
學生36   55   64   62   81   64
學生37   98   52   81   81   85
學生38   87   71   82   84   92
學生39   68   99   62   64   61
學生40   69   68   61   80   62
學生41   61   65   85   97   73
學生42   64  100   98   53   57
學生43   88   64   94   57   83
學生44   60   71   55   82   95
學生45   82   62   58   92   65
學生46  100   89   92   83   95
學生47   73   79   54   98   70
學生48   87   67   83   67   96
學生49   77   77   53   97   89
學生50   94   50   84   91   80

In [7]:
sum = class1['國文'] + class1['英文'] +  class1['數學'] +  class1['自然'] + class1['地理']
sum

學生1     349
學生2     401
學生3     375
學生4     346
學生5     386
學生6     433
學生7     378
學生8     398
學生9     392
學生10    377
學生11    326
學生12    329
學生13    382
學生14    330
學生15    345
學生16    317
學生17    456
學生18    341
學生19    392
學生20    345
學生21    347
學生22    383
學生23    367
學生24    333
學生25    395
學生26    356
學生27    430
學生28    354
學生29    357
學生30    321
學生31    434
學生32    330
學生33    333
學生34    357
學生35    358
學生36    326
學生37    397
學生38    416
學生39    354
學生40    340
學生41    381
學生42    372
學生43    386
學生44    363
學生45    359
學生46    459
學生47    374
學生48    400
學生49    393
學生50    399
dtype: int64

In [11]:
class1['總分'] = sum
class1['平均'] = sum/5
class1['排名'] = sum.rank(method='first',ascending=False)
class1

       國文   英文   數學   自然   地理   總分    平均    排名
學生1    91   53   68   72   65  349  69.8  35.0
學生2    84   88   88   88   53  401  80.2   7.0
學生3    70   79   86   83   57  375  75.0  23.0
學生4    74   59   50   73   90  346  69.2  37.0
學生5    62   79   75   89   81  386  77.2  16.0
學生6    84   91   90   68  100  433  86.6   4.0
學生7    65   50  100   74   89  378  75.6  21.0
學生8    66   95   66   92   79  398  79.6  10.0
學生9    90   50   83   75   94  392  78.4  14.0
學生10   66   99   58   94   60  377  75.4  22.0
學生11   73   59   51   58   85  326  65.2  47.0
學生12   66   73   82   52   56  329  65.8  46.0
學生13   53   54   99   92   84  382  76.4  19.0
學生14   67   75   53   70   65  330  66.0  44.0
學生15   65   68   58   89   65  345  69.0  38.0
學生16   59   57   71   70   60  317  63.4  50.0
學生17   95   90   99   96   76  456  91.2   2.0
學生18   74   54   57   83   73  341  68.2  40.0
學生19   63   89   95   89   56  392  78.4  15.0
學生20   62   60   92   70   61  345  69.0  39.0
學生21   81   79   63   56   68  347  69.4  36.0
學生22   64   80   87  100   52  383  76.6  18.0
學生23   63   58  100   72   74  367  73.4  26.0
學生24   62   71   54   50   96  333  66.6  42.0
學生25   85   78   84   94   54  395  79.0  12.0
學生26   75   68   82   55   76  356  71.2  32.0
學生27   91   76   82   93   88  430  86.0   5.0
學生28   59   58   62   76   99  354  70.8  33.0
學生29   78   80   60   78   61  357  71.4  30.0
學生30   52   62   89   53   65  321  64.2  49.0
學生31   88   77   85   89   95  434  86.8   3.0
學生32   55   82   78   60   55  330  66.0  45.0
學生33   57   96   62   56   62  333  66.6  43.0
學生34   61   62   65   99   70  357  71.4  31.0
學生35   57   60   93   84   64  358  71.6  29.0
學生36   55   64   62   81   64  326  65.2  48.0
學生37   98   52   81   81   85  397  79.4  11.0
學生38   87   71   82   84   92  416  83.2   6.0
學生39   68   99   62   64   61  354  70.8  34.0
學生40   69   68   61   80   62  340  68.0  41.0
學生41   61   65   85   97   73  381  76.2  20.0
學生42   64  100   98   53   57  372  74.4  25.0
學生43   88   64   94   57   83  386  77.2  17.0
學生44   60   71   55   82   95  363  72.6  27.0
學生45   82   62   58   92   65  359  71.8  28.0
學生46  100   89   92   83   95  459  91.8   1.0
學生47   73   79   54   98   70  374  74.8  24.0
學生48   87   67   83   67   96  400  80.0   8.0
學生49   77   77   53   97   89  393  78.6  13.0
學生50   94   50   84   91   80  399  79.8   9.0