In [3]:
import numpy as np
import pandas as pd

scores = np.random.randint(50,101,size=(50,5))
scores

array([[ 91,  53,  68,  72,  65],
       [ 84,  88,  88,  88,  53],
       [ 70,  79,  86,  83,  57],
       [ 74,  59,  50,  73,  90],
       [ 62,  79,  75,  89,  81],
       [ 84,  91,  90,  68, 100],
       [ 65,  50, 100,  74,  89],
       [ 66,  95,  66,  92,  79],
       [ 90,  50,  83,  75,  94],
       [ 66,  99,  58,  94,  60],
       [ 73,  59,  51,  58,  85],
       [ 66,  73,  82,  52,  56],
       [ 53,  54,  99,  92,  84],
       [ 67,  75,  53,  70,  65],
       [ 65,  68,  58,  89,  65],
       [ 59,  57,  71,  70,  60],
       [ 95,  90,  99,  96,  76],
       [ 74,  54,  57,  83,  73],
       [ 63,  89,  95,  89,  56],
       [ 62,  60,  92,  70,  61],
       [ 81,  79,  63,  56,  68],
       [ 64,  80,  87, 100,  52],
       [ 63,  58, 100,  72,  74],
       [ 62,  71,  54,  50,  96],
       [ 85,  78,  84,  94,  54],
       [ 75,  68,  82,  55,  76],
       [ 91,  76,  82,  93,  88],
       [ 59,  58,  62,  76,  99],
       [ 78,  80,  60,  78,  61],
       [ 52,  62,  89,  53,  65],
       [ 88,  77,  85,  89,  95],
       [ 55,  82,  78,  60,  55],
       [ 57,  96,  62,  56,  62],
       [ 61,  62,  65,  99,  70],
       [ 57,  60,  93,  84,  64],
       [ 55,  64,  62,  81,  64],
       [ 98,  52,  81,  81,  85],
       [ 87,  71,  82,  84,  92],
       [ 68,  99,  62,  64,  61],
       [ 69,  68,  61,  80,  62],
       [ 61,  65,  85,  97,  73],
       [ 64, 100,  98,  53,  57],
       [ 88,  64,  94,  57,  83],
       [ 60,  71,  55,  82,  95],
       [ 82,  62,  58,  92,  65],
       [100,  89,  92,  83,  95],
       [ 73,  79,  54,  98,  70],
       [ 87,  67,  83,  67,  96],
       [ 77,  77,  53,  97,  89],
       [ 94,  50,  84,  91,  80]])

In [4]:
class1 = pd.DataFrame(scores,
             index=[f'學生{v}' for v in range(1,51)],
             columns=['國文','英文','數學','自然','地理'])
class1

       國文   英文   數學   自然   地理
學生1    91   53   68   72   65
學生2    84   88   88   88   53
學生3    70   79   86   83   57
學生4    74   59   50   73   90
學生5    62   79   75   89   81
學生6    84   91   90   68  100
學生7    65   50  100   74   89
學生8    66   95   66   92   79
學生9    90   50   83   75   94
學生10   66   99   58   94   60
學生11   73   59   51   58   85
學生12   66   73   82   52   56
學生13   53   54   99   92   84
學生14   67   75   53   70   65
學生15   65   68   58   89   65
學生16   59   57   71   70   60
學生17   95   90   99   96   76
學生18   74   54   57   83   73
學生19   63   89   95   89   56
學生20   62   60   92   70   61
學生21   81   79   63   56   68
學生22   64   80   87  100   52
學生23   63   58  100   72   74
學生24   62   71   54   50   96
學生25   85   78   84   94   54
學生26   75   68   82   55   76
學生27   91   76   82   93   88
學生28   59   58   62   76   99
學生29   78   80   60   78   61
學生30   52   62   89   53   65
學生31   88   77   85   89   95
學生32   55   82   78   60   55
學生33   57   96   62   56   62
學生34   61   62   65   99   70
學生35   57   60   93   84   64
學生36   55   64   62   81   64
學生37   98   52   81   81   85
學生38   87   71   82   84   92
學生39   68   99   62   64   61
學生40   69   68   61   80   62
學生41   61   65   85   97   73
學生42   64  100   98   53   57
學生43   88   64   94   57   83
學生44   60   71   55   82   95
學生45   82   62   58   92   65
學生46  100   89   92   83   95
學生47   73   79   54   98   70
學生48   87   67   83   67   96
學生49   77   77   53   97   89
學生50   94   50   84   91   80