In [1]:
import numpy as np
import pandas as pd

scores=np.random.randint(50, 101, size=(50,5))
scores_pd = pd.DataFrame(scores,columns=['國文', '英文', '數學', '地理', '歷史'],index=range(1,51))
scores_pd.index.name = "學號"
scores_pd.columns.name = "科目"
scores_pd

科目  國文   英文   數學   地理  歷史
學號
1   84   59   64   85  51
2   63  100   72   94  75
3   82   90   58   68  66
4   57   84   90  100  55
5   57   62   92   66  54
6   95   88   61   58  99
7   99   72   73   81  96
8   95   64   93   70  95
9   90   70   76   64  58
10  75   78   53   51  89
11  53   56   56   90  56
12  78   77   52   77  89
13  83   69   96   55  76
14  53   58   93   80  94
15  82   99   54   91  80
16  89   74   86   52  51
17  91   60   89   84  53
18  90   61   84   69  79
19  64  100   57   86  65
20  88   61   67   63  52
21  74   97   60   94  84
22  72   66   64   97  74
23  87   55   55   78  92
24  76   64   68   92  88
25  71   65   79   79  60
26  55   67   98   82  74
27  95   92   74   64  96
28  80   69   64   86  75
29  93   60   59   99  52
30  98   53   93   93  81
31  99   82   65   84  83
32  51   95   53   63  79
33  94   58   70   73  79
34  68   75   99   59  99
35  71   76   98   58  60
36  68   60   56   67  53
37  78   71   74   64  67
38  70   70   88   69  86
39  61   84   93   82  56
40  52   72   65   70  67
41  64   86   72   53  57
42  73   86  100   97  56
43  95   54   85   70  83
44  69   81   93   52  53
45  62   61   58   77  71
46  52   88   97  100  95
47  84   65   67   98  58
48  59   68   94   77  94
49  81   51   85   55  79
50  71   59   50   72  90

In [2]:
scores_pd['國文']

學號
1     84
2     63
3     82
4     57
5     57
6     95
7     99
8     95
9     90
10    75
11    53
12    78
13    83
14    53
15    82
16    89
17    91
18    90
19    64
20    88
21    74
22    72
23    87
24    76
25    71
26    55
27    95
28    80
29    93
30    98
31    99
32    51
33    94
34    68
35    71
36    68
37    78
38    70
39    61
40    52
41    64
42    73
43    95
44    69
45    62
46    52
47    84
48    59
49    81
50    71
Name: 國文, dtype: int64

In [3]:
scores_pd[['國文','數學']]

科目  國文   數學
學號
1   84   64
2   63   72
3   82   58
4   57   90
5   57   92
6   95   61
7   99   73
8   95   93
9   90   76
10  75   53
11  53   56
12  78   52
13  83   96
14  53   93
15  82   54
16  89   86
17  91   89
18  90   84
19  64   57
20  88   67
21  74   60
22  72   64
23  87   55
24  76   68
25  71   79
26  55   98
27  95   74
28  80   64
29  93   59
30  98   93
31  99   65
32  51   53
33  94   70
34  68   99
35  71   98
36  68   56
37  78   74
38  70   88
39  61   93
40  52   65
41  64   72
42  73  100
43  95   85
44  69   93
45  62   58
46  52   97
47  84   67
48  59   94
49  81   85
50  71   50

In [4]:
scores_pd.reindex(['國文','英文'],axis=1)

科目  國文   英文
學號
1   84   59
2   63  100
3   82   90
4   57   84
5   57   62
6   95   88
7   99   72
8   95   64
9   90   70
10  75   78
11  53   56
12  78   77
13  83   69
14  53   58
15  82   99
16  89   74
17  91   60
18  90   61
19  64  100
20  88   61
21  74   97
22  72   66
23  87   55
24  76   64
25  71   65
26  55   67
27  95   92
28  80   69
29  93   60
30  98   53
31  99   82
32  51   95
33  94   58
34  68   75
35  71   76
36  68   60
37  78   71
38  70   70
39  61   84
40  52   72
41  64   86
42  73   86
43  95   54
44  69   81
45  62   61
46  52   88
47  84   65
48  59   68
49  81   51
50  71   59

In [5]:
scores_pd[:5]

科目  國文   英文  數學   地理  歷史
學號
1   84   59  64   85  51
2   63  100  72   94  75
3   82   90  58   68  66
4   57   84  90  100  55
5   57   62  92   66  54

In [6]:
scores_pd.reindex([1,2,3,4,5])

科目  國文   英文  數學   地理  歷史
學號
1   84   59  64   85  51
2   63  100  72   94  75
3   82   90  58   68  66
4   57   84  90  100  55
5   57   62  92   66  54

In [7]:
scores_pd.loc[[1,2,3,4,5]]

科目  國文   英文  數學   地理  歷史
學號
1   84   59  64   85  51
2   63  100  72   94  75
3   82   90  58   68  66
4   57   84  90  100  55
5   57   62  92   66  54

In [8]:
scores_pd.iloc[:5]

科目  國文   英文  數學   地理  歷史
學號
1   84   59  64   85  51
2   63  100  72   94  75
3   82   90  58   68  66
4   57   84  90  100  55
5   57   62  92   66  54

In [9]:
scores_pd.reindex(index=[1,2,3,4,5],columns=['國文','數學','歷史'])

科目  國文  數學  歷史
學號
1   84  64  51
2   63  72  75
3   82  58  66
4   57  90  55
5   57  92  54

In [10]:
scores_pd.loc[1:5,['國文','數學','歷史']]

科目  國文  數學  歷史
學號
1   84  64  51
2   63  72  75
3   82  58  66
4   57  90  55
5   57  92  54

In [11]:
scores_pd.iloc[:5,[0,2,4]]

科目  國文  數學  歷史
學號
1   84  64  51
2   63  72  75
3   82  58  66
4   57  90  55
5   57  92  54

In [12]:
scores_pd

科目  國文   英文   數學   地理  歷史
學號
1   84   59   64   85  51
2   63  100   72   94  75
3   82   90   58   68  66
4   57   84   90  100  55
5   57   62   92   66  54
6   95   88   61   58  99
7   99   72   73   81  96
8   95   64   93   70  95
9   90   70   76   64  58
10  75   78   53   51  89
11  53   56   56   90  56
12  78   77   52   77  89
13  83   69   96   55  76
14  53   58   93   80  94
15  82   99   54   91  80
16  89   74   86   52  51
17  91   60   89   84  53
18  90   61   84   69  79
19  64  100   57   86  65
20  88   61   67   63  52
21  74   97   60   94  84
22  72   66   64   97  74
23  87   55   55   78  92
24  76   64   68   92  88
25  71   65   79   79  60
26  55   67   98   82  74
27  95   92   74   64  96
28  80   69   64   86  75
29  93   60   59   99  52
30  98   53   93   93  81
31  99   82   65   84  83
32  51   95   53   63  79
33  94   58   70   73  79
34  68   75   99   59  99
35  71   76   98   58  60
36  68   60   56   67  53
37  78   71   74   64  67
38  70   70   88   69  86
39  61   84   93   82  56
40  52   72   65   70  67
41  64   86   72   53  57
42  73   86  100   97  56
43  95   54   85   70  83
44  69   81   93   52  53
45  62   61   58   77  71
46  52   88   97  100  95
47  84   65   67   98  58
48  59   68   94   77  94
49  81   51   85   55  79
50  71   59   50   72  90

In [13]:
scores_pd.iloc[0,0] = 60
scores_pd

科目  國文   英文   數學   地理  歷史
學號
1   60   59   64   85  51
2   63  100   72   94  75
3   82   90   58   68  66
4   57   84   90  100  55
5   57   62   92   66  54
6   95   88   61   58  99
7   99   72   73   81  96
8   95   64   93   70  95
9   90   70   76   64  58
10  75   78   53   51  89
11  53   56   56   90  56
12  78   77   52   77  89
13  83   69   96   55  76
14  53   58   93   80  94
15  82   99   54   91  80
16  89   74   86   52  51
17  91   60   89   84  53
18  90   61   84   69  79
19  64  100   57   86  65
20  88   61   67   63  52
21  74   97   60   94  84
22  72   66   64   97  74
23  87   55   55   78  92
24  76   64   68   92  88
25  71   65   79   79  60
26  55   67   98   82  74
27  95   92   74   64  96
28  80   69   64   86  75
29  93   60   59   99  52
30  98   53   93   93  81
31  99   82   65   84  83
32  51   95   53   63  79
33  94   58   70   73  79
34  68   75   99   59  99
35  71   76   98   58  60
36  68   60   56   67  53
37  78   71   74   64  67
38  70   70   88   69  86
39  61   84   93   82  56
40  52   72   65   70  67
41  64   86   72   53  57
42  73   86  100   97  56
43  95   54   85   70  83
44  69   81   93   52  53
45  62   61   58   77  71
46  52   88   97  100  95
47  84   65   67   98  58
48  59   68   94   77  94
49  81   51   85   55  79
50  71   59   50   72  90

In [14]:
scores_pd.loc[2] = [100,100,100,100,100]
scores_pd.loc[1] = scores_pd.loc[1] + 1
scores_pd.iloc[-3:] -= 5

In [15]:
scores_pd

科目   國文   英文   數學   地理   歷史
學號
1    61   60   65   86   52
2   100  100  100  100  100
3    82   90   58   68   66
4    57   84   90  100   55
5    57   62   92   66   54
6    95   88   61   58   99
7    99   72   73   81   96
8    95   64   93   70   95
9    90   70   76   64   58
10   75   78   53   51   89
11   53   56   56   90   56
12   78   77   52   77   89
13   83   69   96   55   76
14   53   58   93   80   94
15   82   99   54   91   80
16   89   74   86   52   51
17   91   60   89   84   53
18   90   61   84   69   79
19   64  100   57   86   65
20   88   61   67   63   52
21   74   97   60   94   84
22   72   66   64   97   74
23   87   55   55   78   92
24   76   64   68   92   88
25   71   65   79   79   60
26   55   67   98   82   74
27   95   92   74   64   96
28   80   69   64   86   75
29   93   60   59   99   52
30   98   53   93   93   81
31   99   82   65   84   83
32   51   95   53   63   79
33   94   58   70   73   79
34   68   75   99   59   99
35   71   76   98   58   60
36   68   60   56   67   53
37   78   71   74   64   67
38   70   70   88   69   86
39   61   84   93   82   56
40   52   72   65   70   67
41   64   86   72   53   57
42   73   86  100   97   56
43   95   54   85   70   83
44   69   81   93   52   53
45   62   61   58   77   71
46   52   88   97  100   95
47   84   65   67   98   58
48   54   63   89   72   89
49   76   46   80   50   74
50   66   54   45   67   85

In [18]:
#統計
scores_sum=scores_pd.sum(axis=1)

In [19]:
scores_mean = scores_pd.mean(axis=1)
scores_mean

學號
1      64.8
2     100.0
3      72.8
4      77.2
5      66.2
6      80.2
7      84.2
8      83.4
9      71.6
10     69.2
11     62.2
12     74.6
13     75.8
14     75.6
15     81.2
16     70.4
17     75.4
18     76.6
19     74.4
20     66.2
21     81.8
22     74.6
23     73.4
24     77.6
25     70.8
26     75.2
27     84.2
28     74.8
29     72.6
30     83.6
31     82.6
32     68.2
33     74.8
34     80.0
35     72.6
36     60.8
37     70.8
38     76.6
39     75.2
40     65.2
41     66.4
42     82.4
43     77.4
44     69.6
45     65.8
46     86.4
47     74.4
48     73.4
49     65.2
50     63.4
dtype: float64

In [20]:
scores_pd['總分'] = scores_sum
scores_pd['平均'] = scores_mean
scores_pd

科目   國文   英文   數學   地理   歷史   總分     平均
學號
1    61   60   65   86   52  324   64.8
2   100  100  100  100  100  500  100.0
3    82   90   58   68   66  364   72.8
4    57   84   90  100   55  386   77.2
5    57   62   92   66   54  331   66.2
6    95   88   61   58   99  401   80.2
7    99   72   73   81   96  421   84.2
8    95   64   93   70   95  417   83.4
9    90   70   76   64   58  358   71.6
10   75   78   53   51   89  346   69.2
11   53   56   56   90   56  311   62.2
12   78   77   52   77   89  373   74.6
13   83   69   96   55   76  379   75.8
14   53   58   93   80   94  378   75.6
15   82   99   54   91   80  406   81.2
16   89   74   86   52   51  352   70.4
17   91   60   89   84   53  377   75.4
18   90   61   84   69   79  383   76.6
19   64  100   57   86   65  372   74.4
20   88   61   67   63   52  331   66.2
21   74   97   60   94   84  409   81.8
22   72   66   64   97   74  373   74.6
23   87   55   55   78   92  367   73.4
24   76   64   68   92   88  388   77.6
25   71   65   79   79   60  354   70.8
26   55   67   98   82   74  376   75.2
27   95   92   74   64   96  421   84.2
28   80   69   64   86   75  374   74.8
29   93   60   59   99   52  363   72.6
30   98   53   93   93   81  418   83.6
31   99   82   65   84   83  413   82.6
32   51   95   53   63   79  341   68.2
33   94   58   70   73   79  374   74.8
34   68   75   99   59   99  400   80.0
35   71   76   98   58   60  363   72.6
36   68   60   56   67   53  304   60.8
37   78   71   74   64   67  354   70.8
38   70   70   88   69   86  383   76.6
39   61   84   93   82   56  376   75.2
40   52   72   65   70   67  326   65.2
41   64   86   72   53   57  332   66.4
42   73   86  100   97   56  412   82.4
43   95   54   85   70   83  387   77.4
44   69   81   93   52   53  348   69.6
45   62   61   58   77   71  329   65.8
46   52   88   97  100   95  432   86.4
47   84   65   67   98   58  372   74.4
48   54   63   89   72   89  367   73.4
49   76   46   80   50   74  326   65.2
50   66   54   45   67   85  317   63.4

In [21]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [25]:
obj.rank(method='first',ascending=False).astype(int)

0    1
1    7
2    2
3    3
4    5
5    6
6    4
dtype: int64

In [28]:
scores_pd['名次'] = scores_sum.rank(method='first',ascending=False).astype(int)

In [29]:
scores_pd

科目   國文   英文   數學   地理   歷史   總分     平均  名次
學號
1    61   60   65   86   52  324   64.8  47
2   100  100  100  100  100  500  100.0   1
3    82   90   58   68   66  364   72.8  31
4    57   84   90  100   55  386   77.2  15
5    57   62   92   66   54  331   66.2  42
6    95   88   61   58   99  401   80.2  11
7    99   72   73   81   96  421   84.2   3
8    95   64   93   70   95  417   83.4   6
9    90   70   76   64   58  358   71.6  34
10   75   78   53   51   89  346   69.2  39
11   53   56   56   90   56  311   62.2  49
12   78   77   52   77   89  373   74.6  25
13   83   69   96   55   76  379   75.8  18
14   53   58   93   80   94  378   75.6  19
15   82   99   54   91   80  406   81.2  10
16   89   74   86   52   51  352   70.4  37
17   91   60   89   84   53  377   75.4  20
18   90   61   84   69   79  383   76.6  16
19   64  100   57   86   65  372   74.4  27
20   88   61   67   63   52  331   66.2  43
21   74   97   60   94   84  409   81.8   9
22   72   66   64   97   74  373   74.6  26
23   87   55   55   78   92  367   73.4  29
24   76   64   68   92   88  388   77.6  13
25   71   65   79   79   60  354   70.8  35
26   55   67   98   82   74  376   75.2  21
27   95   92   74   64   96  421   84.2   4
28   80   69   64   86   75  374   74.8  23
29   93   60   59   99   52  363   72.6  32
30   98   53   93   93   81  418   83.6   5
31   99   82   65   84   83  413   82.6   7
32   51   95   53   63   79  341   68.2  40
33   94   58   70   73   79  374   74.8  24
34   68   75   99   59   99  400   80.0  12
35   71   76   98   58   60  363   72.6  33
36   68   60   56   67   53  304   60.8  50
37   78   71   74   64   67  354   70.8  36
38   70   70   88   69   86  383   76.6  17
39   61   84   93   82   56  376   75.2  22
40   52   72   65   70   67  326   65.2  45
41   64   86   72   53   57  332   66.4  41
42   73   86  100   97   56  412   82.4   8
43   95   54   85   70   83  387   77.4  14
44   69   81   93   52   53  348   69.6  38
45   62   61   58   77   71  329   65.8  44
46   52   88   97  100   95  432   86.4   2
47   84   65   67   98   58  372   74.4  28
48   54   63   89   72   89  367   73.4  30
49   76   46   80   50   74  326   65.2  46
50   66   54   45   67   85  317   63.4  48

In [32]:
scores_pd.sort_values(by='名次')

科目   國文   英文   數學   地理   歷史   總分     平均  名次
學號
2   100  100  100  100  100  500  100.0   1
46   52   88   97  100   95  432   86.4   2
7    99   72   73   81   96  421   84.2   3
27   95   92   74   64   96  421   84.2   4
30   98   53   93   93   81  418   83.6   5
8    95   64   93   70   95  417   83.4   6
31   99   82   65   84   83  413   82.6   7
42   73   86  100   97   56  412   82.4   8
21   74   97   60   94   84  409   81.8   9
15   82   99   54   91   80  406   81.2  10
6    95   88   61   58   99  401   80.2  11
34   68   75   99   59   99  400   80.0  12
24   76   64   68   92   88  388   77.6  13
43   95   54   85   70   83  387   77.4  14
4    57   84   90  100   55  386   77.2  15
18   90   61   84   69   79  383   76.6  16
38   70   70   88   69   86  383   76.6  17
13   83   69   96   55   76  379   75.8  18
14   53   58   93   80   94  378   75.6  19
17   91   60   89   84   53  377   75.4  20
26   55   67   98   82   74  376   75.2  21
39   61   84   93   82   56  376   75.2  22
28   80   69   64   86   75  374   74.8  23
33   94   58   70   73   79  374   74.8  24
12   78   77   52   77   89  373   74.6  25
22   72   66   64   97   74  373   74.6  26
19   64  100   57   86   65  372   74.4  27
47   84   65   67   98   58  372   74.4  28
23   87   55   55   78   92  367   73.4  29
48   54   63   89   72   89  367   73.4  30
3    82   90   58   68   66  364   72.8  31
29   93   60   59   99   52  363   72.6  32
35   71   76   98   58   60  363   72.6  33
9    90   70   76   64   58  358   71.6  34
25   71   65   79   79   60  354   70.8  35
37   78   71   74   64   67  354   70.8  36
16   89   74   86   52   51  352   70.4  37
44   69   81   93   52   53  348   69.6  38
10   75   78   53   51   89  346   69.2  39
32   51   95   53   63   79  341   68.2  40
41   64   86   72   53   57  332   66.4  41
5    57   62   92   66   54  331   66.2  42
20   88   61   67   63   52  331   66.2  43
45   62   61   58   77   71  329   65.8  44
40   52   72   65   70   67  326   65.2  45
49   76   46   80   50   74  326   65.2  46
1    61   60   65   86   52  324   64.8  47
50   66   54   45   67   85  317   63.4  48
11   53   56   56   90   56  311   62.2  49
36   68   60   56   67   53  304   60.8  50

In [33]:
import numpy as np
import pandas as pd

scores=np.random.randint(50, 101, size=(50,5))
scores_pd = pd.DataFrame(scores,columns=['國文', '英文', '數學', '地理', '歷史'],index=range(1,51))
scores_pd.index.name = "學號"
scores_pd.columns.name = "科目"
scores_sum=scores_pd.sum(axis=1)
scores_mean = scores_pd.mean(axis=1)
scores_pd['總分'] = scores_sum
scores_pd['平均'] = scores_mean
scores_pd['名次'] = scores_sum.rank(method='first',ascending=False).astype(int)
scores_pd.sort_values(by='名次')

科目  國文  英文  數學  地理   歷史   總分    平均  名次
學號
7   78  99  95  98   90  460  92.0   1
46  71  87  97  91   91  437  87.4   2
22  87  90  86  67   96  426  85.2   3
29  60  72  98  98   91  419  83.8   4
34  74  88  97  75   76  410  82.0   5
36  75  93  92  73   76  409  81.8   6
32  65  95  80  71   95  406  81.2   7
49  80  94  89  76   66  405  81.0   8
9   78  78  89  57   96  398  79.6   9
33  87  84  54  85   87  397  79.4  10
11  60  96  74  97   69  396  79.2  11
27  92  84  73  65   80  394  78.8  12
5   95  74  86  65   69  389  77.8  13
21  82  95  67  64   81  389  77.8  14
15  68  73  85  98   64  388  77.6  15
40  81  62  88  90   67  388  77.6  16
25  93  57  66  71   99  386  77.2  17
37  67  93  59  92   75  386  77.2  18
8   98  74  66  78   68  384  76.8  19
31  52  95  82  62   91  382  76.4  20
41  98  79  57  53   93  380  76.0  21
50  53  76  94  86   71  380  76.0  22
3   58  86  73  96   65  378  75.6  23
47  95  80  50  53  100  378  75.6  24
14  74  60  99  74   70  377  75.4  25
16  91  89  69  64   63  376  75.2  26
38  80  71  81  55   89  376  75.2  27
39  96  78  63  51   88  376  75.2  28
20  72  60  61  90   91  374  74.8  29
2   58  70  68  93   83  372  74.4  30
48  74  77  61  80   79  371  74.2  31
6   88  56  56  74   96  370  74.0  32
19  62  50  84  81   93  370  74.0  33
13  57  83  84  81   64  369  73.8  34
44  73  88  50  98   58  367  73.4  35
23  91  72  91  54   58  366  73.2  36
28  54  57  64  99   92  366  73.2  37
12  61  78  60  87   77  363  72.6  38
43  62  90  73  61   70  356  71.2  39
24  90  61  56  69   79  355  71.0  40
26  80  76  74  65   56  351  70.2  41
4   82  52  65  91   60  350  70.0  42
1   61  93  65  68   60  347  69.4  43
30  50  81  61  55   99  346  69.2  44
35  51  59  88  66   78  342  68.4  45
42  58  82  67  76   58  341  68.2  46
10  55  52  80  91   62  340  68.0  47
17  50  76  74  77   59  336  67.2  48
18  50  76  58  72   68  324  64.8  49
45  65  74  61  60   60  320  64.0  50